include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    duplicate_ignore: ignore
      
linters:
  rules:
    duplicate_ignore: false