name: emulators
description: A utility library to automate mobile emulators. Wraps `xcrun` for iOS and the Android CLI tools.
version: 0.4.7
repository: https://github.com/tim-smart/dart_emulators.git

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  fpdt: ^0.0.57
  freezed_annotation: ^1.0.0
  json_annotation: ^4.3.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.0.4
  flutter_lints: ^1.0.4
  freezed: ^1.0.0
  json_serializable: ^6.0.1
