name: emulators
description: A new Flutter package project.
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dartz: ^0.10.0-nullsafety.2
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1
  path: ^1.8.0
  rxdart: ^0.27.1

dev_dependencies:
  build_runner: ^2.0.4
  freezed: ^0.14.2
  json_serializable: ^4.1.3
