name: emulators
description: A utility library to automate mobile emulators. Wraps `xcrun` for iOS and the Android CLI tools.
version: 0.1.16
repository: https://github.com/tim-smart/dart_emulators.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  dartz: ^0.10.0-nullsafety.2
  freezed_annotation: ^0.15.0
  json_annotation: ^4.0.1
  path: ^1.8.0
  rxdart: ^0.27.1

dev_dependencies:
  build_runner: ^2.0.4
  freezed: ^0.15.0+1
  json_serializable: ^6.0.0
